version: "3.1"

services:
  collects:
    container_name: collects
    hostname: grp
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: collects
    environment:
      - DATABASE_CA_URL=sqlserver://10.33.136.36:1433;database=mdb_new;user=sa;password=Hiepnhinh09!;encrypt=DANGER_PLAINTEXT
      - GENENARATE_REPORT_API=http://localhost:3002/power-bi

    restart: always
    ports:
      - 3004:3004
    user: root
