version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27016:27017'
    environment:
      MONGO_INITDB_DATABASE: request
  clt:
    container_name: clt
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: collects
    environment:
      - DATABASE_CA_URL: 'sqlserver://10.33.136.36:1433;database=mdb_new;user=sa;password=Hiepnhinh09!;encrypt=DANGER_PLAINTEXT'
      - GENENARATE_REPORT_API: 'http://localhost:3002/power-bi'
      - URI_MONGODB: 'mongodb://mongodb:27017'
    restart: always
    ports:
      - 3004:3004
    user: root
  grp:
    container_name: grp
    hostname: grp
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        module: generate-reports
    environment:
      WORKSPACE_ID: '4f42d374-2271-4740-a5ab-08941273aa02'
      CLIENT_ID: '12915b8c-5394-4728-a041-c3efd9596ff6'
      USERNAME_MS: 'hiepnn9@chipad.onmicrosoft.com'
      PASSWORD: 'Vok89967'
      TENNANT_ID: '0f6d670d7-8f78-4832-908d-1d5e54c11b5d'
    restart: always
    ports:
      - 3002:3002
    user: root
